/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import javax.swing.JTextField;

/**
 *
 * @author agust
 */
public class AddPointPanel extends javax.swing.JPanel {

    /**
     * Creates new form addPointPanel
     */
    public AddPointPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pointX = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pointY = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setPreferredSize(new java.awt.Dimension(500, 300));
        setLayout(new java.awt.GridLayout(3, 1));

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.LEFT);
        flowLayout1.setAlignOnBaseline(true);
        jPanel4.setLayout(flowLayout1);

        jLabel2.setText("Point X");
        jPanel4.add(jLabel2);

        pointX.setPreferredSize(new java.awt.Dimension(80, 28));
        pointX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointXActionPerformed(evt);
            }
        });
        jPanel4.add(pointX);

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("(Ex: 1.8) ");
        jPanel4.add(jLabel4);

        add(jPanel4);

        jPanel5.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jLabel3.setText("Point Y");
        jPanel5.add(jLabel3);

        pointY.setPreferredSize(new java.awt.Dimension(80, 28));
        pointY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pointYActionPerformed(evt);
            }
        });
        jPanel5.add(pointY);

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 153, 153));
        jLabel5.setText("(Ex: 1.8) ");
        jPanel5.add(jLabel5);

        add(jPanel5);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        jScrollPane1.setBorder(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 204, 204));
        jTextArea1.setColumns(40);
        jTextArea1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(102, 102, 102));
        jTextArea1.setRows(5);
        jTextArea1.setText("the values have to be number and the\ndecimals are separated by points.");
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel8.add(jScrollPane1);

        add(jPanel8);
    }// </editor-fold>//GEN-END:initComponents

    private void pointYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointYActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointYActionPerformed

    public double getPointX() {
        return Double.parseDouble(pointX.getText());
    }

    public double getPointY() {
        return Double.parseDouble(pointY.getText());
    }

    private void pointXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pointXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pointXActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField pointX;
    private javax.swing.JTextField pointY;
    // End of variables declaration//GEN-END:variables
}
