/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import elements.Element;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import shortcuts.Sc;

/**
 *
 * @author agust
 */
public class ElementsDescriptionPanel extends javax.swing.JDialog {

    /**
     * Creates new form ElementsDescriptionPanel
     */
    public ElementsDescriptionPanel(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.elementsList = ((Init)parent).getAllElements();
        createFilters(this.elementsList);
        showElements(this.elementsList);
        
   
 //for(Element e: ((Init)parent).getAllElements() ){
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }
    
    private void createFilters(ArrayList<Element> elements){
        
        this.checksDispo = new ArrayList <JCheckBox> ();
        for(String type: Sc.getTypes(elements)){
            
            JCheckBox check = new JCheckBox(type);
            check.setSelected(true);
            check.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent evt) {
                    checkBoxesActionPerformed(evt);
                }
            });
            
            this.jpanelFilters.add( check );
            checksDispo.add( check );
        }
    }

    private void checkBoxesActionPerformed( ActionEvent e){
        boolean isElementToShow = false;
        //JCheckBox check = (JCheckBox)e.getSource();
        
        ArrayList<Element> elementsToShow  = new ArrayList<Element> ();
        for(Element element: this.elementsList ){
            for(JCheckBox check: this.checksDispo)
                if(check.isSelected() && check.getText().toLowerCase().equals(element.getType().toLowerCase()) )
                    elementsToShow.add(element);
        }
        showElements( elementsToShow );
    }
    
    private void showElements(ArrayList<Element> elements){
        String des ="";
        int i = 0;
        for(Element e: elements ){
            des+=e.getElementDescription()+"\n\n";
            i++;
        }
            
        
        this.elementsDescription.setText(des);
        this.ElementsShown.setText("Elements shown: "+((this.elementsList.size()>0)?i+"/"+this.elementsList.size():0));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpanelFilters = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ElementsShown = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        elementsDescription = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 700));

        jPanel1.setLayout(new java.awt.GridLayout(3, 1));

        jLabel1.setText("Filters");
        jPanel2.add(jLabel1);

        jPanel1.add(jPanel2);
        jPanel1.add(jpanelFilters);

        jPanel3.add(ElementsShown);

        jPanel1.add(jPanel3);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        elementsDescription.setEditable(false);
        elementsDescription.setBackground(new java.awt.Color(224, 224, 224));
        elementsDescription.setColumns(20);
        elementsDescription.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        elementsDescription.setForeground(new java.awt.Color(102, 102, 102));
        elementsDescription.setRows(5);
        jScrollPane1.setViewportView(elementsDescription);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
   
    private ArrayList<Element> elementsList;
    private ArrayList<JCheckBox> checksDispo;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ElementsShown;
    private javax.swing.JTextArea elementsDescription;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpanelFilters;
    // End of variables declaration//GEN-END:variables
}
