/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import java.awt.Font;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import say.swing.JFontChooser;

/**
 *
 * @author agust
 */
public class FormMouseEdition extends javax.swing.JDialog {

    /**
     * Creates new form FormFontEdition
     */
    public FormMouseEdition(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mouseSpeed.setValue(((Init)parent).getGraphicSpace().getMouseSpeed());
         this.mouseSpeedValue.setText(""+this.mouseSpeed.getValue());
        
        
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        mouseSpeed = new javax.swing.JSlider();
        mouseSpeedValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(300, 150));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Mouse");
        jPanel1.add(jLabel1);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jLabel4.setText("Mouse Speed");
        jPanel2.add(jLabel4);

        mouseSpeed.setMinimum(1);
        mouseSpeed.setToolTipText("");
        mouseSpeed.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mouseSpeedStateChanged(evt);
            }
        });
        jPanel2.add(mouseSpeed);
        jPanel2.add(mouseSpeedValue);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mouseSpeedStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mouseSpeedStateChanged
       ((Init)this.getParent()).getGraphicSpace().setMouseSpeed(this.mouseSpeed.getValue());
        this.mouseSpeedValue.setText(""+this.mouseSpeed.getValue());
    }//GEN-LAST:event_mouseSpeedStateChanged

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSlider mouseSpeed;
    private javax.swing.JLabel mouseSpeedValue;
    // End of variables declaration//GEN-END:variables
}
