/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import elements.Circle;
import elements.Line;
import elements.Point;
import elements.Rectangle;
import elements.Triangle;
import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.JButton;
import javax.swing.JColorChooser;
import javax.swing.JFrame;

/**
 *
 * @author agust
 */
public class FormColorEdition extends javax.swing.JDialog {

    /**
     * Creates new form FormColorEdition
     */
    public FormColorEdition(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initButtonColors();
        
        //transparence
        int transparenceValue = (int) ( ((Init)this.getParent()).getGraphicSpace().getFillTransparence() *100);
        this.tranparenceSlider.setValue(transparenceValue);
        //System.out.println(transparenceValue);
        setTransparence ( transparenceValue );
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pointDefaultColor = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabell15 = new javax.swing.JLabel();
        pointMouseColor = new javax.swing.JButton();
        jPanel22 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lineDefaultColor = new javax.swing.JButton();
        jPanel23 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        lineMouseColor = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        circleDefaultColor = new javax.swing.JButton();
        jPanel25 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        circleMouseColor = new javax.swing.JButton();
        jPanel26 = new javax.swing.JPanel();
        jPanel28 = new javax.swing.JPanel();
        jPanel29 = new javax.swing.JPanel();
        jLabell16 = new javax.swing.JLabel();
        triangleDefaultColor = new javax.swing.JButton();
        jPanel30 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        triangleMouseColor = new javax.swing.JButton();
        jPanel31 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        rectangleDefaultColor = new javax.swing.JButton();
        jPanel32 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        rectangleMouseColor = new javax.swing.JButton();
        jPanel33 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        functionDefaultColor = new javax.swing.JButton();
        jPanel34 = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        functionMouseColor = new javax.swing.JButton();
        jPanel20 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        tranparenceSlider = new javax.swing.JSlider();
        transpaenceLabel = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        backgroundColor = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        Jlabel6 = new javax.swing.JLabel();
        labelsColor = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        JLabel7 = new javax.swing.JLabel();
        gridsColor = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        JLabel8 = new javax.swing.JLabel();
        axesColor = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel27 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        visibleElementColor = new javax.swing.JButton();
        jPanel19 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        noVisibleElement = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        jPanel35 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        selectedElementColor = new javax.swing.JButton();
        jPanel36 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        abstractElementColor = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Colors");
        jPanel2.add(jLabel1);

        getContentPane().add(jPanel2, java.awt.BorderLayout.NORTH);

        jPanel1.setLayout(new java.awt.GridLayout(4, 1));

        jPanel3.setLayout(new java.awt.BorderLayout());

        jPanel6.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Elements color ");
        jPanel6.add(jLabel2);

        jPanel3.add(jPanel6, java.awt.BorderLayout.NORTH);

        jPanel7.setLayout(new java.awt.GridLayout(3, 2));

        java.awt.FlowLayout flowLayout1 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout1.setAlignOnBaseline(true);
        jPanel4.setLayout(flowLayout1);

        jLabel3.setText("Point (default Color)");
        jPanel4.add(jLabel3);

        pointDefaultColor.setPreferredSize(new java.awt.Dimension(20, 20));
        pointDefaultColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel4.add(pointDefaultColor);

        jPanel7.add(jPanel4);

        jPanel8.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        jLabell15.setText("Point (Mouse over color)");
        jPanel8.add(jLabell15);

        pointMouseColor.setPreferredSize(new java.awt.Dimension(20, 20));
        pointMouseColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel8.add(pointMouseColor);

        jPanel7.add(jPanel8);

        java.awt.FlowLayout flowLayout3 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout3.setAlignOnBaseline(true);
        jPanel22.setLayout(flowLayout3);

        jLabel7.setText("Line (default color)");
        jPanel22.add(jLabel7);

        lineDefaultColor.setPreferredSize(new java.awt.Dimension(20, 20));
        lineDefaultColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel22.add(lineDefaultColor);

        jPanel7.add(jPanel22);

        java.awt.FlowLayout flowLayout4 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout4.setAlignOnBaseline(true);
        jPanel23.setLayout(flowLayout4);

        jLabel8.setText("Line (Mouse over color)");
        jPanel23.add(jLabel8);

        lineMouseColor.setPreferredSize(new java.awt.Dimension(20, 20));
        lineMouseColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel23.add(lineMouseColor);

        jPanel7.add(jPanel23);

        java.awt.FlowLayout flowLayout5 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout5.setAlignOnBaseline(true);
        jPanel24.setLayout(flowLayout5);

        jLabel9.setText("Circle (default color)");
        jPanel24.add(jLabel9);

        circleDefaultColor.setPreferredSize(new java.awt.Dimension(20, 20));
        circleDefaultColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel24.add(circleDefaultColor);

        jPanel7.add(jPanel24);

        java.awt.FlowLayout flowLayout6 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout6.setAlignOnBaseline(true);
        jPanel25.setLayout(flowLayout6);

        jLabel14.setText("Circle (Mouse over color)");
        jPanel25.add(jLabel14);

        circleMouseColor.setPreferredSize(new java.awt.Dimension(20, 20));
        circleMouseColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel25.add(circleMouseColor);

        jPanel7.add(jPanel25);

        jPanel3.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel3);

        jPanel26.setLayout(new java.awt.BorderLayout());

        jPanel28.setLayout(new java.awt.GridLayout(3, 2));

        jPanel29.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        jLabell16.setText("Triangle (default color)");
        jPanel29.add(jLabell16);

        triangleDefaultColor.setPreferredSize(new java.awt.Dimension(20, 20));
        triangleDefaultColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel29.add(triangleDefaultColor);

        jPanel28.add(jPanel29);

        java.awt.FlowLayout flowLayout7 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout7.setAlignOnBaseline(true);
        jPanel30.setLayout(flowLayout7);

        jLabel16.setText("Triangle (Mouse over color)");
        jPanel30.add(jLabel16);

        triangleMouseColor.setPreferredSize(new java.awt.Dimension(20, 20));
        triangleMouseColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel30.add(triangleMouseColor);

        jPanel28.add(jPanel30);

        java.awt.FlowLayout flowLayout8 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout8.setAlignOnBaseline(true);
        jPanel31.setLayout(flowLayout8);

        jLabel17.setText("Rectangle (default color)");
        jPanel31.add(jLabel17);

        rectangleDefaultColor.setPreferredSize(new java.awt.Dimension(20, 20));
        rectangleDefaultColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel31.add(rectangleDefaultColor);

        jPanel28.add(jPanel31);

        java.awt.FlowLayout flowLayout9 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout9.setAlignOnBaseline(true);
        jPanel32.setLayout(flowLayout9);

        jLabel18.setText("Rectangle (Mouse over color)");
        jPanel32.add(jLabel18);

        rectangleMouseColor.setPreferredSize(new java.awt.Dimension(20, 20));
        rectangleMouseColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel32.add(rectangleMouseColor);

        jPanel28.add(jPanel32);

        java.awt.FlowLayout flowLayout10 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout10.setAlignOnBaseline(true);
        jPanel33.setLayout(flowLayout10);

        jLabel19.setText("Functions (default color)");
        jPanel33.add(jLabel19);

        functionDefaultColor.setPreferredSize(new java.awt.Dimension(20, 20));
        functionDefaultColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel33.add(functionDefaultColor);

        jPanel28.add(jPanel33);

        java.awt.FlowLayout flowLayout11 = new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5);
        flowLayout11.setAlignOnBaseline(true);
        jPanel34.setLayout(flowLayout11);

        jLabel20.setText("Functions (Mouse over color)");
        jPanel34.add(jLabel20);

        functionMouseColor.setPreferredSize(new java.awt.Dimension(20, 20));
        functionMouseColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel34.add(functionMouseColor);

        jPanel28.add(jPanel34);

        jPanel26.add(jPanel28, java.awt.BorderLayout.CENTER);

        java.awt.FlowLayout flowLayout2 = new java.awt.FlowLayout(java.awt.FlowLayout.CENTER, 20, 5);
        flowLayout2.setAlignOnBaseline(true);
        jPanel20.setLayout(flowLayout2);

        jLabel13.setText("Fill transparence");
        jPanel20.add(jLabel13);

        tranparenceSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tranparenceSliderStateChanged(evt);
            }
        });
        jPanel20.add(tranparenceSlider);

        transpaenceLabel.setText("50%");
        jPanel20.add(transpaenceLabel);

        jPanel26.add(jPanel20, java.awt.BorderLayout.SOUTH);

        jPanel1.add(jPanel26);

        jPanel5.setLayout(new java.awt.BorderLayout());

        jPanel9.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 153, 153));
        jLabel5.setText("Space grapherc colors  ");
        jPanel9.add(jLabel5);

        jPanel5.add(jPanel9, java.awt.BorderLayout.NORTH);

        jPanel10.setLayout(new java.awt.GridLayout(2, 2));

        jPanel11.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        jLabel6.setText("Background Color");
        jPanel11.add(jLabel6);

        backgroundColor.setPreferredSize(new java.awt.Dimension(20, 20));
        backgroundColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel11.add(backgroundColor);

        jPanel10.add(jPanel11);

        jPanel12.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        Jlabel6.setText("Labels Color");
        jPanel12.add(Jlabel6);

        labelsColor.setPreferredSize(new java.awt.Dimension(20, 20));
        labelsColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel12.add(labelsColor);

        jPanel10.add(jPanel12);

        jPanel13.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        JLabel7.setText("Grids Color");
        jPanel13.add(JLabel7);

        gridsColor.setPreferredSize(new java.awt.Dimension(20, 20));
        gridsColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel13.add(gridsColor);

        jPanel10.add(jPanel13);

        jPanel14.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        JLabel8.setText("Axes Color");
        jPanel14.add(JLabel8);

        axesColor.setPreferredSize(new java.awt.Dimension(20, 20));
        axesColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel14.add(axesColor);

        jPanel10.add(jPanel14);

        jPanel5.add(jPanel10, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel5);

        jPanel15.setLayout(new java.awt.BorderLayout());

        jPanel16.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 20, 5));

        jLabel10.setFont(new java.awt.Font("Tahoma", 2, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("List colors");
        jPanel16.add(jLabel10);

        jPanel15.add(jPanel16, java.awt.BorderLayout.NORTH);

        jPanel27.setLayout(new java.awt.GridLayout(2, 1));

        jPanel17.setLayout(new java.awt.GridLayout(1, 2));

        jPanel18.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        jLabel11.setText("Visible Element Color ");
        jPanel18.add(jLabel11);

        visibleElementColor.setPreferredSize(new java.awt.Dimension(20, 20));
        visibleElementColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel18.add(visibleElementColor);

        jPanel17.add(jPanel18);

        jPanel19.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        jLabel12.setText("No Visible Element Color");
        jPanel19.add(jLabel12);

        noVisibleElement.setPreferredSize(new java.awt.Dimension(20, 20));
        noVisibleElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel19.add(noVisibleElement);

        jPanel17.add(jPanel19);

        jPanel27.add(jPanel17);

        jPanel21.setLayout(new java.awt.GridLayout(1, 2));

        jPanel35.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        jLabel15.setText("Selected Element Color");
        jPanel35.add(jLabel15);

        selectedElementColor.setPreferredSize(new java.awt.Dimension(20, 20));
        selectedElementColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel35.add(selectedElementColor);

        jPanel21.add(jPanel35);

        jPanel36.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.RIGHT, 20, 5));

        jLabel4.setText("Abstract Element Color");
        jPanel36.add(jLabel4);

        abstractElementColor.setPreferredSize(new java.awt.Dimension(20, 20));
        abstractElementColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btColorsActionPerformed(evt);
            }
        });
        jPanel36.add(abstractElementColor);

        jPanel21.add(jPanel36);

        jPanel27.add(jPanel21);

        jPanel15.add(jPanel27, java.awt.BorderLayout.CENTER);

        jPanel1.add(jPanel15);

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btColorsActionPerformed
        JButton bt = (JButton)evt.getSource();
        JColorChooser ventanaDeColores=new JColorChooser();
        Color color = ventanaDeColores.showDialog(null, "Chose one color", bt.getBackground());

        if(bt.equals(backgroundColor))
            ((Init)this.getParent()).getGraphicSpace().setBackground(color);
        else if(bt.equals(axesColor))
            ((Init)this.getParent()).getGraphicSpace().setColorAxes(color);
        else if(bt.equals(gridsColor))
            ((Init)this.getParent()).getGraphicSpace().setColorGrid(color);    
        else if(bt.equals(labelsColor))
            ((Init)this.getParent()).getGraphicSpace().setColorLabels(color);
        
        
        else if(bt.equals(noVisibleElement))
            ((Init)this.getParent()).getList().setBackground(color); 
        else if(bt.equals(selectedElementColor))
            ((Init)this.getParent()).getList().setSelectionBackground(color);    
        else if(bt.equals(visibleElementColor))
           ((GraphicElementCellRendered) ((Init)this.getParent()).getList().getCellRenderer()).setVisibleElementColor(color);
        else if(bt.equals(abstractElementColor))
           ((GraphicElementCellRendered) ((Init)this.getParent()).getList().getCellRenderer()).setAbstractElementColor(color);
      
        
        
        else if(bt.equals(pointDefaultColor))
            Point.setNormalColor(color);
        else if(bt.equals(pointMouseColor))
            Point.setMouseOverColor(color);
        else if(bt.equals(lineDefaultColor))
            Line.setNormalColor(color);
        else if(bt.equals(lineMouseColor))
            Line.setMouseOverColor(color);
        else if(bt.equals(circleDefaultColor))
            Circle.setNormalColor(color);
        else if(bt.equals(circleMouseColor))
            Circle.setMouseOverColor(color);
        else if(bt.equals(triangleDefaultColor))
            Triangle.setNormalColor(color);
        else if(bt.equals(triangleMouseColor))
            Triangle.setMouseOverColor(color);
        else if(bt.equals(rectangleDefaultColor))
            Rectangle.setNormalColor(color);
        else if(bt.equals(rectangleMouseColor))
            Rectangle.setMouseOverColor(color);
        /*
        else if(bt.equals(functionDefaultColor))
            Point.setNormalColor(color);
        else if(bt.equals(functionMouseColor))
            Point.setMouseOverColor(color);*/
       initButtonColors();
       ((Init)this.getParent()).getGraphicSpace().repaint();
       ((Init)this.getParent()).getList().repaint();
    }//GEN-LAST:event_btColorsActionPerformed

    private void tranparenceSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tranparenceSliderStateChanged
        setTransparence(this.tranparenceSlider.getValue());
    }//GEN-LAST:event_tranparenceSliderStateChanged

    private void setTransparence(int value){
        ((Init)this.getParent()).getGraphicSpace().setFillTransparence(((double)value)/100);
        this.transpaenceLabel.setText( value+"%" );
        ((Init)this.getParent()).getGraphicSpace().repaint();
    }
    private void initButtonColors(){
        
 
            backgroundColor.setBackground(((Init)this.getParent()).getGraphicSpace().getBackground());
            axesColor.setBackground(((Init)this.getParent()).getGraphicSpace().getColorAxes());
            gridsColor.setBackground( ((Init)this.getParent()).getGraphicSpace().getColorGrid() );    
            labelsColor.setBackground( ((Init)this.getParent()).getGraphicSpace().getColorLabels() ); 

        
        
            noVisibleElement.setBackground( ((Init)this.getParent()).getList().getBackground() ); 
            selectedElementColor.setBackground( ((Init)this.getParent()).getList().getSelectionBackground() ); 
            visibleElementColor.setBackground(((GraphicElementCellRendered) ((Init)this.getParent()).getList().getCellRenderer()).getVisibleElementColor());
            abstractElementColor.setBackground(((GraphicElementCellRendered) ((Init)this.getParent()).getList().getCellRenderer()).getAbstractElementColor());

            
            pointDefaultColor.setBackground( Point.getNormalColor()  );  
            pointMouseColor.setBackground( Point.getMouseOverColor()  );
            lineDefaultColor.setBackground(   Line.getNormalColor() );
            lineMouseColor.setBackground( Line.getMouseOverColor()  );
            circleDefaultColor.setBackground( Circle.getNormalColor()  );
            circleMouseColor.setBackground(  Circle.getMouseOverColor()  );
            triangleDefaultColor.setBackground(  Triangle.getNormalColor()  );
            triangleMouseColor.setBackground(  Triangle.getMouseOverColor() );
            rectangleDefaultColor.setBackground(  Rectangle.getNormalColor()  );
            rectangleMouseColor.setBackground(  Rectangle.getMouseOverColor() );

        
    }
    /**
     * @param args the command line arguments
     */
   
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabel7;
    private javax.swing.JLabel JLabel8;
    private javax.swing.JLabel Jlabel6;
    private javax.swing.JButton abstractElementColor;
    private javax.swing.JButton axesColor;
    private javax.swing.JButton backgroundColor;
    private javax.swing.JButton circleDefaultColor;
    private javax.swing.JButton circleMouseColor;
    private javax.swing.JButton functionDefaultColor;
    private javax.swing.JButton functionMouseColor;
    private javax.swing.JButton gridsColor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabell15;
    private javax.swing.JLabel jLabell16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel25;
    private javax.swing.JPanel jPanel26;
    private javax.swing.JPanel jPanel27;
    private javax.swing.JPanel jPanel28;
    private javax.swing.JPanel jPanel29;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel30;
    private javax.swing.JPanel jPanel31;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel33;
    private javax.swing.JPanel jPanel34;
    private javax.swing.JPanel jPanel35;
    private javax.swing.JPanel jPanel36;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JButton labelsColor;
    private javax.swing.JButton lineDefaultColor;
    private javax.swing.JButton lineMouseColor;
    private javax.swing.JButton noVisibleElement;
    private javax.swing.JButton pointDefaultColor;
    private javax.swing.JButton pointMouseColor;
    private javax.swing.JButton rectangleDefaultColor;
    private javax.swing.JButton rectangleMouseColor;
    private javax.swing.JButton selectedElementColor;
    private javax.swing.JSlider tranparenceSlider;
    private javax.swing.JLabel transpaenceLabel;
    private javax.swing.JButton triangleDefaultColor;
    private javax.swing.JButton triangleMouseColor;
    private javax.swing.JButton visibleElementColor;
    // End of variables declaration//GEN-END:variables
}
