/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package windows;

import elements.Circle;
import elements.Element;
import elements.Line;
import elements.Point;
import elements.Rectangle;
import elements.Triangle;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import shortcuts.Sc;

/**
 *
 * @author agust
 */
public class FormAddElement extends javax.swing.JDialog {

    /**
     * Creates new form formAddElement
     */

    public FormAddElement(java.awt.Frame parent, boolean modal, String lastComponentAdded) {
        super(parent, modal);
        initComponents();
        addForm(lastComponentAdded);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setLocationRelativeTo(parent);
        this.addElementList.setSelectedItem(lastComponentAdded);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        addElementList = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        colorSelected = new javax.swing.JButton();
        panelForm = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        preview = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        addElement = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));

        addElementList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Point", "Line", "Circle", "Triangle", "Rectangle" }));
        addElementList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addElementListActionPerformed(evt);
            }
        });
        jPanel1.add(addElementList);

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel7.setBackground(new java.awt.Color(102, 102, 255));
        jPanel7.setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Color");
        jPanel5.add(jLabel1);

        colorSelected.setText(" ");
        colorSelected.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                colorSelectedActionPerformed(evt);
            }
        });
        jPanel5.add(colorSelected);

        jPanel7.add(jPanel5, java.awt.BorderLayout.SOUTH);

        panelForm.setBackground(new java.awt.Color(0, 153, 153));
        panelForm.setLayout(new java.awt.GridLayout(1, 1));
        jPanel7.add(panelForm, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel7, java.awt.BorderLayout.CENTER);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setPreferredSize(new java.awt.Dimension(300, 329));
        jPanel4.setLayout(new java.awt.GridLayout(1, 1));

        preview.setBackground(new java.awt.Color(255, 255, 255));
        preview.setBorder(null);
        preview.setFocusable(false);
        preview.setOpaque(false);
        preview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previewActionPerformed(evt);
            }
        });
        jPanel4.add(preview);

        jPanel2.add(jPanel4, java.awt.BorderLayout.EAST);

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        addElement.setText("Add");
        addElement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addElementActionPerformed(evt);
            }
        });
        jPanel6.add(addElement);

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel6.add(cancel);

        getContentPane().add(jPanel6, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addElementListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addElementListActionPerformed
        JComboBox liste = (JComboBox)evt.getSource();
        addForm(liste.getSelectedItem().toString());

        //System.out.println(liste.getSelectedItem().toString());
    }//GEN-LAST:event_addElementListActionPerformed

    private void addElementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addElementActionPerformed
        try{
            
       
        Element e=null;
        switch (addElementList.getSelectedItem().toString().toLowerCase()){
            case "point":
                AddPointPanel p = (AddPointPanel)actualPanel;
                e = new Point(p.getPointX(), p.getPointY());
            break;
            
            case "line":
                AddLinePanel  l= (AddLinePanel)actualPanel;
                e = new Line(new Point( l.getPointAX(), l.getPointAY()),
                           new Point( l.getPointBX(), l.getPointBY()));
            break;
            
            case "triangle":
                AddTrianglePanel  t= (AddTrianglePanel)actualPanel;
                e = new Triangle(new Point( t.getPointAX(), t.getPointAY()),
                            new Point( t.getPointBX(), t.getPointBY()),
                            new Point( t.getPointCX(), t.getPointCY()));
                ((Triangle) e).setFill(t.isFill());
            break;
            
            case "rectangle":
                AddRectanglePanel  r= (AddRectanglePanel)actualPanel;
                e = new Rectangle(new Point( r.getInitX(), r.getInitY()), r.getRectangleWidth(), r.getRectangleHeight());
                ((Rectangle) e).setFill(r.isFill());
            break;
            
            case "circle":
                AddCirclePanel  c= (AddCirclePanel)actualPanel;
                e = new Circle(new Point( c.getCenterX(), c.getCenterY()),
                                   c.getRadius());
                ((Circle) e).setFill(c.isFill());
            break;
        }
        
            
        if( e!=null ){
            if(this.color != null)
                e.setColor(this.color);
            ((Init)this.getParent()).addElement(e);
        }
        this.setVisible(false);
        this.dispose();
         }catch(Exception e){
            JOptionPane.showMessageDialog(this, Sc.firstToUpper(e.getMessage()) + "\nPlease fill the boxes with valid data", "Error", JOptionPane.ERROR_MESSAGE);
         }

    }//GEN-LAST:event_addElementActionPerformed

    private void previewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_previewActionPerformed

    private void colorSelectedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorSelectedActionPerformed
        JColorChooser ventanaDeColores=new JColorChooser();
       setColor(ventanaDeColores.showDialog(null, "Seleccione un Color", Color.gray));
   

    }//GEN-LAST:event_colorSelectedActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void addForm(String type){
        panelForm.removeAll();
        switch (type.toLowerCase()){
            case "point":
                actualPanel =new AddPointPanel();
                this.panelForm.add(actualPanel);              
            break;
            
            case "line":
                actualPanel =new AddLinePanel();
                this.panelForm.add(actualPanel);
            break;
            
            case "triangle":
                actualPanel =new AddTrianglePanel();
                this.panelForm.add(actualPanel);
            break;
            
            case "rectangle":
                actualPanel =new AddRectanglePanel();
                this.panelForm.add(actualPanel);
            break;
            
            
            case "circle":
                actualPanel =new AddCirclePanel();
                this.panelForm.add(actualPanel);
            break;
        }
        this.preview.setIcon(new ImageIcon("src/sources/"+type.toLowerCase()+"1.gif"));
        panelForm.updateUI();
    }
  
    private void setColor(Color color){
        if(color != null){
            this.color = color;
            this.colorSelected.setBackground(color);
        }
            
    }
    private JPanel actualPanel;
    private Color color;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addElement;
    private javax.swing.JComboBox<String> addElementList;
    private javax.swing.JButton cancel;
    private javax.swing.JButton colorSelected;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel panelForm;
    private javax.swing.JButton preview;
    // End of variables declaration//GEN-END:variables


}
